
import { 
  Utensils, 
  Car, 
  ShoppingBag, 
  Gamepad2, 
  HeartPulse, 
  Home, 
  Zap, 
  Book, 
  Sparkles, 
  Banknote, 
  Briefcase, 
  Gift, 
  TrendingUp,
  CreditCard,
  PiggyBank,
  Wallet,
  Building,
  Smartphone,
  Globe,
  Coffee,
  Plane,
  Camera,
  Shirt,
  Film,
  Dumbbell,
  GraduationCap,
  Hammer,
  Lamp,
  Waves,
  Wifi,
  Tv,
  Music,
  ShoppingBasket,
  Truck,
  Scissors,
  Cross,
  Stethoscope,
  Smile,
  Gamepad,
  Gamepad2 as JoyStick,
  Beer,
  Pizza,
  Moon,
  Sun,
  User,
  Users,
  Settings,
  Shield,
  Star,
  Heart,
  Flag,
  Map,
  Navigation,
  Compass,
  Anchor,
  Clock,
  Calendar,
  Bell,
  Archive,
  Inbox,
  Link as LinkIcon,
  Search,
  MessageCircle,
  MoreHorizontal
} from 'lucide-react';

export const CATEGORY_ICONS = [
  { name: 'Utensils', icon: Utensils },
  { name: 'Car', icon: Car },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'HeartPulse', icon: HeartPulse },
  { name: 'Home', icon: Home },
  { name: 'Zap', icon: Zap },
  { name: 'Book', icon: Book },
  { name: 'Sparkles', icon: Sparkles },
  { name: 'Banknote', icon: Banknote },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Gift', icon: Gift },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'Wallet', icon: Wallet },
  { name: 'Building', icon: Building },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Globe', icon: Globe },
  { name: 'Coffee', icon: Coffee },
  { name: 'Plane', icon: Plane },
  { name: 'Camera', icon: Camera },
  { name: 'Shirt', icon: Shirt },
  { name: 'Film', icon: Film },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Hammer', icon: Hammer },
  { name: 'Lamp', icon: Lamp },
  { name: 'Waves', icon: Waves },
  { name: 'Wifi', icon: Wifi },
  { name: 'Tv', icon: Tv },
  { name: 'Music', icon: Music },
  { name: 'ShoppingBasket', icon: ShoppingBasket },
  { name: 'Truck', icon: Truck },
  { name: 'Scissors', icon: Scissors },
  { name: 'Smile', icon: Smile },
  { name: 'Beer', icon: Beer },
  { name: 'Pizza', icon: Pizza },
];

export const getIconByName = (name: string) => {
  const found = CATEGORY_ICONS.find(i => i.name === name);
  return found ? found.icon : Wallet;
};
