
import { 
  Utensils, 
  Car, 
  ShoppingBag, 
  Gamepad2, 
  HeartPulse, 
  Home, 
  Zap, 
  Book, 
  Sparkles, 
  Banknote, 
  Briefcase, 
  Gift, 
  TrendingUp,
  CreditCard,
  PiggyBank,
  Wallet,
  Building,
  Smartphone,
  Globe,
  Coffee,
  Plane,
  Camera,
  Shirt,
  Film,
  Dumbbell,
  GraduationCap,
  Hammer,
  Lamp,
  Waves,
  Wifi,
  Tv,
  Music,
  ShoppingBasket,
  Truck,
  Scissors,
  Smile,
  Beer,
  Pizza,
  Landmark,
  BadgeDollarSign,
  CircleDollarSign,
  Bitcoin,
  Receipt,
  FileText,
  Activity,
  ChartPie,
  Code,
  Wrench,
  Baby,
  Bus,
  Train,
  Trophy,
  Umbrella,
  Tent,
  Stethoscope,
  Microscope,
  Ghost,
  Palette,
  Brush,
  Droplet,
  Flame,
  Leaf,
  Cloud,
  Moon,
  Bike,
  Rocket,
  Trees,
  Dog,
  Cat,
  Fish,
  UtensilsCrossed,
  Ship,
  TrainFront,
  TrainTrack,
  PlaneTakeoff,
  PlaneLanding,
  Hotel,
  Tickets,
  Ticket,
  MapPin,
  Laptop,
  Monitor,
  Watch,
  Headphones,
  Radio,
  BookOpen,
  Apple,
  Croissant,
  GlassWater,
  Wine,
  Martini,
  Cake,
  IceCream,
  Popcorn,
  Video,
  Clapperboard,
  Speaker,
  Mic,
  PenTool,
  Library,
  Scale,
  Building2,
  Factory,
  Flower2,
  ScissorsLineDashed,
  Cross,
  Gamepad,
  Gamepad2 as JoyStick,
  Sun,
  User,
  Users,
  Settings,
  Shield,
  Star,
  Heart,
  Flag,
  Map,
  Navigation,
  Compass,
  Anchor,
  Clock,
  Calendar,
  Bell,
  Archive,
  Inbox,
  Link as LinkIcon,
  Search,
  MessageCircle,
  MoreHorizontal,
  Coins,
  HandCoins,
  WalletCards,
  Sofa,
  Store,
  Package,
  Luggage,
  Pill,
  BriefcaseMedical
} from 'lucide-react';

export const CATEGORY_ICONS = [
  { name: 'Utensils', icon: Utensils },
  { name: 'UtensilsCrossed', icon: UtensilsCrossed },
  { name: 'Coffee', icon: Coffee },
  { name: 'Beer', icon: Beer },
  { name: 'Wine', icon: Wine },
  { name: 'Martini', icon: Martini },
  { name: 'GlassWater', icon: GlassWater },
  { name: 'Apple', icon: Apple },
  { name: 'Croissant', icon: Croissant },
  { name: 'Cake', icon: Cake },
  { name: 'IceCream', icon: IceCream },
  { name: 'Pizza', icon: Pizza },
  { name: 'Popcorn', icon: Popcorn },
  { name: 'Car', icon: Car },
  { name: 'Bus', icon: Bus },
  { name: 'Train', icon: Train },
  { name: 'TrainFront', icon: TrainFront },
  { name: 'TrainTrack', icon: TrainTrack },
  { name: 'Plane', icon: Plane },
  { name: 'PlaneTakeoff', icon: PlaneTakeoff },
  { name: 'PlaneLanding', icon: PlaneLanding },
  { name: 'Ship', icon: Ship },
  { name: 'Bike', icon: Bike },
  { name: 'Rocket', icon: Rocket },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'ShoppingBasket', icon: ShoppingBasket },
  { name: 'Shirt', icon: Shirt },
  { name: 'Gamepad', icon: Gamepad },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'JoyStick', icon: JoyStick },
  { name: 'HeartPulse', icon: HeartPulse },
  { name: 'Stethoscope', icon: Stethoscope },
  { name: 'Microscope', icon: Microscope },
  { name: 'Pill', icon: Pill },
  { name: 'BriefcaseMedical', icon: BriefcaseMedical },
  { name: 'Home', icon: Home },
  { name: 'Building', icon: Building },
  { name: 'Building2', icon: Building2 },
  { name: 'Hotel', icon: Hotel },
  { name: 'Store', icon: Store },
  { name: 'Sofa', icon: Sofa },
  { name: 'Zap', icon: Zap },
  { name: 'Book', icon: Book },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Library', icon: Library },
  { name: 'Sparkles', icon: Sparkles },
  { name: 'Banknote', icon: Banknote },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Package', icon: Package },
  { name: 'Luggage', icon: Luggage },
  { name: 'Gift', icon: Gift },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'Wallet', icon: Wallet },
  { name: 'WalletCards', icon: WalletCards },
  { name: 'Landmark', icon: Landmark },
  { name: 'BadgeDollarSign', icon: BadgeDollarSign },
  { name: 'CircleDollarSign', icon: CircleDollarSign },
  { name: 'Coins', icon: Coins },
  { name: 'HandCoins', icon: HandCoins },
  { name: 'Bitcoin', icon: Bitcoin },
  { name: 'Receipt', icon: Receipt },
  { name: 'FileText', icon: FileText },
  { name: 'Activity', icon: Activity },
  { name: 'ChartPie', icon: ChartPie },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Laptop', icon: Laptop },
  { name: 'Monitor', icon: Monitor },
  { name: 'Watch', icon: Watch },
  { name: 'Headphones', icon: Headphones },
  { name: 'Radio', icon: Radio },
  { name: 'Globe', icon: Globe },
  { name: 'Camera', icon: Camera },
  { name: 'Video', icon: Video },
  { name: 'Clapperboard', icon: Clapperboard },
  { name: 'Speaker', icon: Speaker },
  { name: 'Mic', icon: Mic },
  { name: 'Film', icon: Film },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Hammer', icon: Hammer },
  { name: 'Wrench', icon: Wrench },
  { name: 'Lamp', icon: Lamp },
  { name: 'Waves', icon: Waves },
  { name: 'Wifi', icon: Wifi },
  { name: 'Tv', icon: Tv },
  { name: 'Music', icon: Music },
  { name: 'Truck', icon: Truck },
  { name: 'Scissors', icon: Scissors },
  { name: 'ScissorsLineDashed', icon: ScissorsLineDashed },
  { name: 'Smile', icon: Smile },
  { name: 'Ghost', icon: Ghost },
  { name: 'Baby', icon: Baby },
  { name: 'Trophy', icon: Trophy },
  { name: 'Umbrella', icon: Umbrella },
  { name: 'Tent', icon: Tent },
  { name: 'MapPin', icon: MapPin },
  { name: 'Tickets', icon: Tickets },
  { name: 'Ticket', icon: Ticket },
  { name: 'Palette', icon: Palette },
  { name: 'Brush', icon: Brush },
  { name: 'PenTool', icon: PenTool },
  { name: 'Droplet', icon: Droplet },
  { name: 'Flame', icon: Flame },
  { name: 'Leaf', icon: Leaf },
  { name: 'Flower2', icon: Flower2 },
  { name: 'Trees', icon: Trees },
  { name: 'Cloud', icon: Cloud },
  { name: 'Moon', icon: Moon },
  { name: 'Sun', icon: Sun },
  { name: 'Dog', icon: Dog },
  { name: 'Cat', icon: Cat },
  { name: 'Fish', icon: Fish },
  { name: 'Code', icon: Code },
  { name: 'Scale', icon: Scale },
  { name: 'Factory', icon: Factory },
  { name: 'Cross', icon: Cross },
  { name: 'User', icon: User },
  { name: 'Users', icon: Users },
  { name: 'Settings', icon: Settings },
  { name: 'Shield', icon: Shield },
  { name: 'Star', icon: Star },
  { name: 'Heart', icon: Heart },
  { name: 'Flag', icon: Flag },
  { name: 'Map', icon: Map },
  { name: 'Navigation', icon: Navigation },
  { name: 'Compass', icon: Compass },
  { name: 'Anchor', icon: Anchor },
  { name: 'Clock', icon: Clock },
  { name: 'Calendar', icon: Calendar },
  { name: 'Bell', icon: Bell },
  { name: 'Archive', icon: Archive },
  { name: 'Inbox', icon: Inbox },
  { name: 'LinkIcon', icon: LinkIcon },
  { name: 'Search', icon: Search },
  { name: 'MessageCircle', icon: MessageCircle },
  { name: 'MoreHorizontal', icon: MoreHorizontal }
];

export const getIconByName = (name: string) => {
  const found = CATEGORY_ICONS.find(i => i.name === name);
  return found ? found.icon : Wallet;
};
