import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../db';
import { TransactionType, Transaction } from '../types';
import { cn, getCurrencySymbol } from '../lib/utils';
import { 
  ArrowLeft, 
  Check, 
  Calendar, 
  Tag, 
  FileText, 
  Wallet as WalletIcon, 
  Camera,
  X
} from 'lucide-react';
import { motion } from 'motion/react';
import { getIconByName } from '../lib/icons';
import { format, parseISO } from 'date-fns';

import { toast } from 'sonner';

export default function AddTransaction() {
  const navigate = useNavigate();
  const { id } = useParams();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const categoriesLive = useLiveQuery(() => db.categories.toArray());
  const accountsLive = useLiveQuery(() => db.accounts.toArray());
  const settings = useLiveQuery(() => db.settings.get(1));

  const categories = React.useMemo(() => {
    return categoriesLive ? [...categoriesLive].sort((a,b) => (a.order || 0) - (b.order || 0)) : undefined;
  }, [categoriesLive]);

  const accounts = React.useMemo(() => {
    return accountsLive ? [...accountsLive].sort((a,b) => (a.order || 0) - (b.order || 0)) : undefined;
  }, [accountsLive]);

  const [type, setType] = useState<TransactionType>('expense');
  const [amount, setAmount] = useState('');
  const [title, setTitle] = useState('');
  const [categoryId, setCategoryId] = useState<string | number>('');
  const [accountId, setAccountId] = useState<string | number>('');
  const [date, setDate] = useState(() => {
    const d = new Date();
    const offset = d.getTimezoneOffset();
    const localDate = new Date(d.getTime() - (offset * 60 * 1000));
    return localDate.toISOString().split('T')[0];
  });
  const [note, setNote] = useState('');
  const [attachment, setAttachment] = useState<string | undefined>();
  const [showNotes, setShowNotes] = useState(false);

  // Helper to handle category selection and title pre-fill
  const handleCategorySelect = (catId: string | number) => {
    if (!categories) return;
    const cat = categories.find(c => c.id === catId);
    if (!cat) return;

    let newCategoryId = catId;
    let newTitle = cat.name;

    // If it's a parent category, check for subcategories
    if (!cat.parentId) {
      const subCat = categories.find(c => c.parentId === catId);
      if (subCat) {
        newCategoryId = subCat.id!;
        newTitle = `${cat.name} - ${subCat.name}`;
      }
    } else {
      // It's a subcategory
      const parentCat = categories.find(c => c.id === cat.parentId);
      if (parentCat) {
        newTitle = `${parentCat.name} - ${cat.name}`;
      }
    }

    setCategoryId(newCategoryId);
    
    // Only update title if it's empty or matches a known pattern/category name
    const isTitleAutoGenerated = !title || categories.some(c => {
      if (c.name === title) return true;
      const p = categories.find(pc => pc.id === c.parentId);
      if (p && `${p.name} - ${c.name}` === title) return true;
      return false;
    });

    if (isTitleAutoGenerated) {
      setTitle(newTitle);
    }
  };

  // Reset category when type changes or on initial load
  useEffect(() => {
    if (categories && !id) {
      const currentCat = categoryId ? categories.find(c => c.id === categoryId) : null;
      if (!currentCat || currentCat.type !== type) {
        const firstValidParent = categories.find(c => c.type === type && !c.parentId);
        if (firstValidParent) {
          handleCategorySelect(firstValidParent.id!);
        }
      }
    }
  }, [type, categories, id]);

  useEffect(() => {
    if (id) {
      db.transactions.get(Number(id)).then(t => {
        if (t) {
          setType(t.type);
          setAmount(t.amount.toString());
          setTitle(t.title);
          setCategoryId(t.categoryId);
          setAccountId(t.accountId);
          setDate(new Date(t.date).toISOString().split('T')[0]);
          setNote(t.note || '');
          setAttachment(t.attachment);
          if (t.note || t.attachment) {
            setShowNotes(true);
          }
        }
      });
    }
  }, [id]);

  useEffect(() => {
    if (accounts && !accountId && accounts.length > 0) {
      setAccountId(accounts[0].id!);
    }
  }, [accounts]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setAttachment(reader.result as string);
        toast.success('Image attached');
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount || !title || !categoryId || !accountId) {
      toast.error('Please fill all required fields');
      return;
    }

    const data: Transaction = {
      title,
      amount: parseFloat(amount),
      type,
      categoryId: Number(categoryId),
      accountId: Number(accountId),
      date: new Date(date),
      note,
      attachment
    };

    try {
      if (id) {
         await db.transactions.put({ ...data, id: Number(id) });
         toast.success('Transaction updated');
      } else {
         await db.transactions.add(data);
         toast.success('Transaction saved');
      }
      navigate(-1);
    } catch (err) {
      toast.error('Failed to save transaction');
    }
  };

  return (
    <div className="space-y-4 pb-4">
      <div className="flex items-center justify-between">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 rounded-full hover:bg-gray-100 transition-colors">
          <ArrowLeft className="w-6 h-6 text-gray-700" />
        </button>
        <h1 className="text-xl font-bold text-gray-900">{id ? 'Edit' : 'Add'} Transaction</h1>
        <div className="w-10"></div>
      </div>

      <div className="flex p-1 bg-gray-100 rounded-2xl">
        <button 
          type="button"
          onClick={() => setType('expense')}
          className={cn("flex-1 py-2 text-sm font-bold rounded-xl transition-all", type === 'expense' ? "bg-white text-indigo-600 shadow-sm" : "text-gray-500")}
        >
          Expense
        </button>
        <button 
          type="button"
          onClick={() => setType('income')}
          className={cn("flex-1 py-2 text-sm font-bold rounded-xl transition-all", type === 'income' ? "bg-white text-emerald-600 shadow-sm" : "text-gray-500")}
        >
          Income
        </button>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="space-y-4">
          <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-50 space-y-4">
            {/* Title Section */}
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-600 shrink-0">
                <Tag className="w-6 h-6" />
              </div>
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">What for?</label>
                <input 
                  type="text" 
                  placeholder="e.g. Starbucks, Rent, Salary" 
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  className="w-full text-base font-bold focus:outline-none placeholder:text-gray-200 bg-transparent"
                  required
                />
              </div>
            </div>
            
            <div className="h-px bg-gray-50" />

            {/* Amount Section */}
            <div className="flex items-center space-x-4">
              <div className={cn(
                "w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 transition-colors",
                type === 'expense' ? "bg-rose-50 text-rose-600" : "bg-emerald-50 text-emerald-600"
              )}>
                <span className="text-xl font-black">{getCurrencySymbol(settings?.currency)}</span>
              </div>
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Amount</label>
                <input 
                  type="number" 
                  inputMode="decimal"
                  placeholder="0.00"
                  value={amount}
                  onChange={e => setAmount(e.target.value)}
                  className={cn(
                    "w-full text-3xl font-black focus:outline-none placeholder:text-gray-100 bg-transparent tracking-tight transition-colors",
                    type === 'expense' ? "text-rose-500" : "text-emerald-500"
                  )}
                  required
                />
              </div>
            </div>

            <div className="h-px bg-gray-50" />

            <div className="grid grid-cols-2 gap-3">
               <div className="flex items-center space-x-3">
                <div className="w-10 h-10 rounded-2xl bg-orange-50 flex items-center justify-center text-orange-600 shrink-0">
                  <Calendar className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <label className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block ml-0.5">Date</label>
                  <div className="relative">
                    <p className="text-xs font-bold text-gray-900 absolute inset-0 flex items-center pointer-events-none">
                      {date ? format(parseISO(date), 'dd MMM yyyy') : 'Select Date'}
                    </p>
                    <input 
                      type="date" 
                      value={date}
                      onChange={e => setDate(e.target.value)}
                      className="w-full text-xs font-bold focus:outline-none bg-transparent opacity-0 relative z-10 min-h-[1.25rem]"
                      required
                    />
                  </div>
                </div>
               </div>
               
               <div className="flex items-center space-x-3 border-l border-gray-100 pl-4">
                <div className="w-10 h-10 rounded-2xl bg-violet-50 flex items-center justify-center text-violet-600 shrink-0">
                  <WalletIcon className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <label className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block ml-0.5">Account</label>
                  <select 
                    value={accountId}
                    onChange={e => setAccountId(e.target.value)}
                    className="w-full text-xs font-bold focus:outline-none bg-transparent appearance-none truncate"
                    required
                  >
                    {accounts?.map(acc => (
                      <option key={acc.id} value={acc.id}>{acc.name}</option>
                    ))}
                  </select>
                </div>
               </div>
            </div>
          </div>

          <div className="space-y-2 px-1">
             <p className="text-xs text-gray-500 font-bold uppercase tracking-widest">Category</p>
             <div className="flex overflow-x-auto pb-3 gap-3 no-scrollbar">
                {categories?.filter(c => c.type === type && !c.parentId).map(c => {
                  const IconComp = getIconByName(c.icon || 'Tag');
                  const isSelected = categoryId === c.id || categories.find(cat => cat.id === categoryId)?.parentId === c.id;
                  return (
                    <button 
                      key={c.id} 
                      type="button"
                      onClick={() => handleCategorySelect(c.id!)}
                      className={cn(
                        "flex flex-col items-center justify-center p-3 rounded-2xl border-2 transition-all space-y-2 min-w-[84px] shrink-0",
                        isSelected ? "border-indigo-600 bg-white shadow-sm" : "border-transparent bg-white shadow-sm"
                      )}
                    >
                      <div 
                        className="w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-sm"
                        style={{ backgroundColor: c.color }}
                      >
                        <IconComp className="w-5 h-5" />
                      </div>
                      <span className="text-[10px] font-bold text-gray-700 truncate w-full text-center">{c.name}</span>
                    </button>
                  );
                })}
             </div>
          </div>

          {/* Subcategories */}
          {categories?.some(c => c.parentId === categoryId || c.parentId === categories.find(cat => cat.id === categoryId)?.parentId) && (
            <div className="space-y-2 px-1">
               <p className="text-xs text-gray-500 font-bold uppercase tracking-widest">Sub-category</p>
               <div className="flex overflow-x-auto pb-3 gap-2.5 no-scrollbar">
                  {categories.filter(c => c.parentId === categoryId || (c.parentId && c.parentId === categories.find(cat => cat.id === categoryId)?.parentId)).map(c => {
                    const IconComp = getIconByName(c.icon || 'Tag');
                    const isSelected = categoryId === c.id;
                    return (
                      <button 
                        key={c.id} 
                        type="button"
                        onClick={() => handleCategorySelect(c.id!)}
                        className={cn(
                          "flex items-center space-x-2 px-3 py-2 rounded-xl border-2 transition-all shrink-0 w-auto",
                          isSelected ? "border-indigo-600 bg-white shadow-sm" : "border-transparent bg-white shadow-sm hover:border-gray-100"
                        )}
                      >
                       <div 
                          className="w-7 h-7 rounded-lg flex items-center justify-center text-white shadow-sm flex-shrink-0"
                          style={{ backgroundColor: c.color }}
                        >
                          <IconComp className="w-3.5 h-3.5" />
                        </div>
                        <span className={cn(
                          "text-[11px] font-bold whitespace-nowrap",
                          isSelected ? "text-indigo-900" : "text-gray-600"
                        )}>{c.name}</span>
                      </button>
                    );
                  })}
               </div>
            </div>
          )}

          {!showNotes ? (
            <button 
              type="button"
              onClick={() => setShowNotes(true)}
              className="w-full py-3 border-2 border-dashed border-gray-100 rounded-2xl text-gray-400 font-bold text-xs uppercase tracking-widest hover:border-indigo-200 hover:text-indigo-400 transition-all flex items-center justify-center space-x-2"
            >
              <FileText className="w-4 h-4" />
              <span>Add Notes & Photo</span>
            </button>
          ) : (
            <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-50 space-y-4 animate-in fade-in zoom-in-95 duration-200">
              <div className="flex items-center justify-between text-gray-400">
                <div className="flex items-center space-x-3">
                  <FileText className="w-5 h-5" />
                  <span className="text-xs font-bold uppercase tracking-widest">Notes & Attachments</span>
                </div>
                <button 
                  type="button" 
                  onClick={() => setShowNotes(false)}
                  className="text-[10px] font-bold text-rose-500 uppercase tracking-widest"
                >
                  Hide
                </button>
              </div>
              
              <textarea 
                placeholder="Add more details..."
                value={note}
                onChange={e => setNote(e.target.value)}
                className="w-full text-sm font-medium focus:outline-none min-h-[80px] bg-gray-50/50 rounded-2xl p-4"
              />

              <div className="flex items-center space-x-3">
                 {attachment ? (
                   <div className="relative w-16 h-16 rounded-2xl overflow-hidden shadow-sm ring-2 ring-indigo-100">
                      <img src={attachment} className="w-full h-full object-cover" alt="receipt" />
                      <button 
                        type="button" 
                        onClick={() => setAttachment(undefined)}
                        className="absolute top-1 right-1 p-0.5 bg-red-500 text-white rounded-full shadow-lg"
                      >
                        <X className="w-3 h-3" />
                      </button>
                   </div>
                 ) : (
                   <button 
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="w-16 h-16 rounded-2xl bg-gray-50 border-2 border-dashed border-gray-200 flex flex-col items-center justify-center text-gray-400 hover:bg-gray-100 hover:border-indigo-200 transition-colors"
                   >
                     <Camera className="w-5 h-5 mb-1" />
                     <span className="text-[8px] font-bold uppercase tracking-tighter">Add Photo</span>
                   </button>
                 )}
                 <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  className="hidden" 
                  accept="image/*"
                 />
                 <div className="flex-1 flex flex-col justify-center">
                    <p className="text-[10px] font-bold text-gray-400 uppercase tracking-tight">Attachment</p>
                    <p className="text-[10px] text-gray-300 font-medium leading-tight">Keep a photo of your receipt for tax or returns.</p>
                 </div>
              </div>
            </div>
          )}
        </div>

        <div className="pt-2">
          <button 
            type="submit"
            className="w-full bg-indigo-600 text-white py-3.5 rounded-2xl font-bold shadow-xl shadow-indigo-100 active:scale-[0.98] transition-transform flex items-center justify-center space-x-2"
          >
            <Check className="w-5 h-5" />
            <span>Save Transaction</span>
          </button>
        </div>
      </form>
    </div>
  );
}

