import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../db';
import { TransactionType, Transaction } from '../types';
import { cn, getCurrencySymbol, formatNumberOnly } from '../lib/utils';
import { saveFile, getFileUri, getRawFileUri, deleteFile } from '../lib/fileStorage';
import { 
  ArrowLeft, 
  Check, 
  Calendar, 
  Tag, 
  FileText, 
  Wallet as WalletIcon, 
  Camera,
  X,
  FileIcon,
  Eye
} from 'lucide-react';
import { motion } from 'motion/react';
import { getIconByName } from '../lib/icons';
import { format, parseISO } from 'date-fns';

import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import { toast } from 'sonner';

export default function AddTransaction() {
  const navigate = useNavigate();
  const { id } = useParams();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const categoriesLive = useLiveQuery(() => db.categories.toArray());
  const accountsLive = useLiveQuery(() => db.accounts.toArray());
  const settings = useLiveQuery(() => db.settings.get(1));

  const categories = React.useMemo(() => {
    return categoriesLive ? [...categoriesLive].sort((a,b) => (a.order || 0) - (b.order || 0)) : undefined;
  }, [categoriesLive]);

  const accounts = React.useMemo(() => {
    return accountsLive ? [...accountsLive].sort((a,b) => (a.order || 0) - (b.order || 0)) : undefined;
  }, [accountsLive]);

  const [type, setType] = useState<TransactionType>('expense');
  const [amount, setAmount] = useState('');
  const [title, setTitle] = useState('');
  const [categoryId, setCategoryId] = useState<string | number>('');
  const [accountId, setAccountId] = useState<string | number>('');
  const [toAccountId, setToAccountId] = useState<string | number>('');
  const [date, setDate] = useState(() => {
    const d = new Date();
    const offset = d.getTimezoneOffset();
    const localDate = new Date(d.getTime() - (offset * 60 * 1000));
    return localDate.toISOString().split('T')[0];
  });
  const [note, setNote] = useState('');
  const [attachment, setAttachment] = useState<string | undefined>();
  const [attachmentUri, setAttachmentUri] = useState<string | undefined>();
  const [attachmentFile, setAttachmentFile] = useState<File | null>(null);
  const [showNotes, setShowNotes] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  // Helper to handle category selection and title pre-fill
  const handleCategorySelect = (catId: string | number) => {
    if (!categories) return;
    const cat = categories.find(c => c.id === catId);
    if (!cat) return;

    let newCategoryId = catId;
    let newTitle = cat.name;

    // If it's a parent category, check for subcategories
    if (!cat.parentId) {
      const subCat = categories.find(c => c.parentId === catId);
      if (subCat) {
        newCategoryId = subCat.id!;
        newTitle = `${cat.name} - ${subCat.name}`;
      }
    } else {
      // It's a subcategory
      const parentCat = categories.find(c => c.id === cat.parentId);
      if (parentCat) {
        newTitle = `${parentCat.name} - ${cat.name}`;
      }
    }

    setCategoryId(newCategoryId);
    
    // Only update title if it's empty, 'Transfer', or matches a known pattern/category name
    const isTitleAutoGenerated = !title || title === 'Transfer' || categories.some(c => {
      if (c.name === title) return true;
      const p = categories.find(pc => pc.id === c.parentId);
      if (p && `${p.name} - ${c.name}` === title) return true;
      return false;
    });

    if (isTitleAutoGenerated) {
      setTitle(newTitle);
    }
  };

  // Reset category when type changes or on initial load
  useEffect(() => {
    if (categories && !id && type !== 'transfer') {
      const currentCat = categoryId ? categories.find(c => c.id === categoryId) : null;
      if (!currentCat || currentCat.type !== type) {
        const firstValidParent = categories.find(c => c.type === type && !c.parentId);
        if (firstValidParent) {
          handleCategorySelect(firstValidParent.id!);
        }
      } else {
        if (title === 'Transfer') {
          handleCategorySelect(categoryId as string | number);
        }
      }
    } else if (type === 'transfer' && !id) {
       setTitle('Transfer');
    }
  }, [type, categories, id, categoryId, title]);

  useEffect(() => {
    if (id) {
      db.transactions.get(Number(id)).then(async t => {
        if (t) {
          setType(t.type);
          setAmount(t.amount.toString());
          setTitle(t.title);
          setCategoryId(t.categoryId);
          setAccountId(t.accountId);
          setToAccountId(t.toAccountId || '');
          setDate(new Date(t.date).toISOString().split('T')[0]);
          setNote(t.note || '');
          setAttachment(t.attachment);
          if (t.attachment) {
            // Check if it's a legacy base64 or a filename
            if (t.attachment.startsWith('data:')) {
              setAttachmentUri(t.attachment);
            } else {
              try {
                const uri = await getFileUri(t.attachment);
                setAttachmentUri(uri);
              } catch (e) {
                console.error('Failed to get attachment URI', e);
              }
            }
          }
          if (t.note || t.attachment) {
            setShowNotes(true);
          }
        }
      });
    }
  }, [id]);

  useEffect(() => {
    if (accounts && !accountId && accounts.length > 0) {
      setAccountId(accounts[0].id!);
    }
    if (accounts && !toAccountId && accounts.length > 1) {
      setToAccountId(accounts[1].id!);
    } else if (accounts && !toAccountId && accounts.length > 0) {
      setToAccountId(accounts[0].id!);
    }
  }, [accounts]);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate only image upload
      if (!file.type.startsWith('image/')) {
        toast.error('Please upload an image file (Receipt Photo)');
        if (fileInputRef.current) fileInputRef.current.value = '';
        return;
      }

      // Validate file size (e.g., 5MB)
      if (file.size > 5 * 1024 * 1024) {
        toast.error('File too large (max 5MB)');
        if (fileInputRef.current) fileInputRef.current.value = '';
        return;
      }
      
      setAttachmentFile(file);
      
      // Create a temporary object URL for previewing/viewing before save
      const tempUri = URL.createObjectURL(file);
      setAttachmentUri(tempUri);
      
      setAttachment(file.name); // Temporary name display
      toast.success('File attached');
    }
  };

  const handleViewFile = async () => {
    if (!attachmentUri) {
      toast.error('No file URI available');
      return;
    }

    // For images, we can show internal preview
    if (attachment?.match(/\.(jpg|jpeg|png|gif|webp)$/i) || attachmentUri.startsWith('data:image')) {
      setShowPreview(true);
      return;
    }

    if (Capacitor.isNativePlatform() && attachment && !attachment.startsWith('data:')) {
      try {
        const rawUri = await getRawFileUri(attachment);
        await Share.share({
          title: attachment,
          files: [rawUri]
        });
      } catch (e) {
        window.open(attachmentUri, '_blank');
      }
    } else {
      window.open(attachmentUri, '_blank');
    }
  };

  const handleAmountChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let rawValue = e.target.value;
    const numberFormat = settings?.numberFormat || 'in';
    
    // Depending on the format, clean up the input into a standard float string
    if (numberFormat === 'eu') {
      // EU format: dot is thousand separator, comma is decimal
      rawValue = rawValue.replace(/\./g, '').replace(/,/g, '.');
    } else {
      // US/IN format: comma is thousand separator, dot is decimal
      rawValue = rawValue.replace(/,/g, '');
    }

    // Keep only numbers and at most one decimal point
    rawValue = rawValue.replace(/[^0-9.]/g, '');
    const parts = rawValue.split('.');
    if (parts.length > 2) {
      rawValue = parts[0] + '.' + parts.slice(1).join('');
    }
    
    setAmount(rawValue);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount || !title || !accountId || (type !== 'transfer' && !categoryId)) {
      toast.error('Please fill all required fields');
      return;
    }
    if (type === 'transfer' && (!toAccountId || String(accountId) === String(toAccountId))) {
      toast.error('Please select different accounts for transfer');
      return;
    }

    let finalAttachment = attachment;
    if (attachmentFile) {
      try {
        finalAttachment = await saveFile(attachmentFile);
      } catch (err) {
        toast.error('Failed to save attachment');
        return;
      }
    }

    const data: Transaction = {
      title,
      amount: parseFloat(amount),
      type,
      categoryId: type === 'transfer' ? 0 : Number(categoryId),
      accountId: Number(accountId),
      ...(type === 'transfer' && { toAccountId: Number(toAccountId) }),
      date: new Date(date),
      note,
      attachment: finalAttachment
    };

    try {
      if (id) {
         await db.transactions.put({ ...data, id: Number(id) });
         toast.success('Transaction updated');
      } else {
         await db.transactions.add(data);
         toast.success('Transaction saved');
      }
      navigate(-1);
    } catch (err) {
      toast.error('Failed to save transaction');
    }
  };

  return (
    <div className="space-y-4 pb-4">
      <div className="flex items-center justify-between">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 rounded-full hover:bg-gray-100 transition-colors">
          <ArrowLeft className="w-6 h-6 text-gray-700" />
        </button>
        <h1 className="text-xl font-bold text-gray-900">{id ? 'Edit' : 'Add'} Transaction</h1>
        <div className="w-10"></div>
      </div>

      <div className="flex p-1 bg-gray-100 rounded-2xl overflow-x-auto no-scrollbar">
        <button 
          type="button"
          onClick={() => setType('expense')}
          className={cn("flex-1 px-4 py-2 text-sm font-bold rounded-xl transition-all whitespace-nowrap", type === 'expense' ? "bg-white text-indigo-600 shadow-sm" : "text-gray-500")}
        >
          Expense
        </button>
        <button 
          type="button"
          onClick={() => setType('income')}
          className={cn("flex-1 px-4 py-2 text-sm font-bold rounded-xl transition-all whitespace-nowrap", type === 'income' ? "bg-white text-emerald-600 shadow-sm" : "text-gray-500")}
        >
          Income
        </button>
        <button 
          type="button"
          onClick={() => setType('transfer')}
          className={cn("flex-1 px-4 py-2 text-sm font-bold rounded-xl transition-all whitespace-nowrap", type === 'transfer' ? "bg-white text-blue-600 shadow-sm" : "text-gray-500")}
        >
          Transfer
        </button>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="space-y-4">
          <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-50 space-y-4">
            {/* Title Section */}
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-600 shrink-0">
                <Tag className="w-6 h-6" />
              </div>
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">What for?</label>
                <input 
                  type="text" 
                  placeholder="e.g. Starbucks, Rent, Salary" 
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  className="w-full text-base font-bold focus:outline-none placeholder:text-gray-200 bg-transparent"
                  required
                />
              </div>
            </div>
            
            <div className="h-px bg-gray-50" />

            {/* Amount Section */}
            <div className="flex items-center space-x-4">
              <div className={cn(
                "w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 transition-colors",
                type === 'expense' ? "bg-rose-50 text-rose-600" : type === 'income' ? "bg-emerald-50 text-emerald-600" : "bg-blue-50 text-blue-600"
              )}>
                <span className="text-xl font-black">{getCurrencySymbol(settings)}</span>
              </div>
              <div className="flex-1 space-y-1">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Amount</label>
                <input 
                  type="text" 
                  inputMode="decimal"
                  placeholder="0.00"
                  value={amount ? formatNumberOnly(amount, settings) : ''}
                  onChange={handleAmountChange}
                  className={cn(
                    "w-full text-3xl font-black focus:outline-none placeholder:text-gray-100 bg-transparent tracking-tight transition-colors",
                    type === 'expense' ? "text-rose-500" : type === 'income' ? "text-emerald-500" : "text-blue-500"
                  )}
                  required
                />
              </div>
            </div>

            <div className="h-px bg-gray-50" />

            <div className="grid grid-cols-2 gap-3">
               <div className="flex items-center space-x-3">
                <div className="w-10 h-10 rounded-2xl bg-orange-50 flex items-center justify-center text-orange-600 shrink-0">
                  <Calendar className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <label className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block ml-0.5">Date</label>
                  <div className="relative">
                    <p className="text-xs font-bold text-gray-900 absolute inset-0 flex items-center pointer-events-none">
                      {date ? format(parseISO(date), 'dd MMM yyyy') : 'Select Date'}
                    </p>
                    <input 
                      type="date" 
                      value={date}
                      onChange={e => setDate(e.target.value)}
                      className="w-full text-xs font-bold focus:outline-none bg-transparent opacity-0 relative z-10 min-h-[1.25rem]"
                      required
                    />
                  </div>
                </div>
               </div>
               
               <div className="flex items-center space-x-3 border-l border-gray-100 pl-4">
                <div className="w-10 h-10 rounded-2xl bg-violet-50 flex items-center justify-center text-violet-600 shrink-0">
                  <WalletIcon className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <label className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block ml-0.5">{type === 'transfer' ? 'From' : 'Account'}</label>
                  <select 
                    value={accountId}
                    onChange={e => setAccountId(e.target.value)}
                    className="w-full text-xs font-bold focus:outline-none bg-transparent appearance-none truncate"
                    required
                  >
                    {accounts?.map(acc => (
                      <option key={acc.id} value={acc.id}>{acc.name}</option>
                    ))}
                  </select>
                </div>
               </div>
            </div>

            {type === 'transfer' && (
              <>
                <div className="h-px bg-gray-50" />
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600 shrink-0">
                    <WalletIcon className="w-5 h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <label className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block ml-0.5">To Account</label>
                    <select 
                      value={toAccountId}
                      onChange={e => setToAccountId(e.target.value)}
                      className="w-full text-xs font-bold focus:outline-none bg-transparent appearance-none truncate"
                      required
                    >
                      {accounts?.map(acc => (
                        <option key={acc.id} value={acc.id}>{acc.name}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </>
            )}
            
          </div>

          {type !== 'transfer' && (
            <>
              <div className="space-y-2 px-1">
             <p className="text-xs text-gray-500 font-bold uppercase tracking-widest">Category</p>
             <div className="flex overflow-x-auto pb-3 gap-3 no-scrollbar">
                {categories?.filter(c => c.type === type && !c.parentId).map(c => {
                  const IconComp = getIconByName(c.icon || 'Tag');
                  const isSelected = categoryId === c.id || categories.find(cat => cat.id === categoryId)?.parentId === c.id;
                  return (
                    <button 
                      key={c.id} 
                      type="button"
                      onClick={() => handleCategorySelect(c.id!)}
                      className={cn(
                        "flex flex-col items-center justify-center p-3 rounded-2xl border-2 transition-all space-y-2 min-w-[84px] shrink-0",
                        isSelected ? "border-indigo-600 bg-white shadow-sm" : "border-transparent bg-white shadow-sm"
                      )}
                    >
                      <div 
                        className="w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-sm"
                        style={{ backgroundColor: c.color }}
                      >
                        <IconComp className="w-5 h-5" />
                      </div>
                      <span className="text-[10px] font-bold text-gray-700 truncate w-full text-center">{c.name}</span>
                    </button>
                  );
                })}
             </div>
          </div>

          {/* Subcategories */}
           {categories?.some(c => c.parentId === categoryId || c.parentId === categories.find(cat => cat.id === categoryId)?.parentId) && (
            <div className="space-y-2 px-1">
               <p className="text-xs text-gray-500 font-bold uppercase tracking-widest">Sub-category</p>
               <div className="flex overflow-x-auto pb-3 gap-2.5 no-scrollbar">
                  {categories.filter(c => c.parentId === categoryId || (c.parentId && c.parentId === categories.find(cat => cat.id === categoryId)?.parentId)).map(c => {
                    const IconComp = getIconByName(c.icon || 'Tag');
                    const isSelected = categoryId === c.id;
                    return (
                      <button 
                        key={c.id} 
                        type="button"
                        onClick={() => handleCategorySelect(c.id!)}
                        className={cn(
                          "flex items-center space-x-2 px-3 py-2 rounded-xl border-2 transition-all shrink-0 w-auto",
                          isSelected ? "border-indigo-600 bg-white shadow-sm" : "border-transparent bg-white shadow-sm hover:border-gray-100"
                        )}
                      >
                       <div 
                          className="w-7 h-7 rounded-lg flex items-center justify-center text-white shadow-sm flex-shrink-0"
                          style={{ backgroundColor: c.color }}
                        >
                          <IconComp className="w-3.5 h-3.5" />
                        </div>
                        <span className={cn(
                          "text-[11px] font-bold whitespace-nowrap",
                          isSelected ? "text-indigo-900" : "text-gray-600"
                        )}>{c.name}</span>
                      </button>
                    );
                  })}
               </div>
            </div>
          )}
          </>
          )}

          {!showNotes ? (
            <button 
              type="button"
              onClick={() => setShowNotes(true)}
              className="w-full py-3 border-2 border-dashed border-gray-100 rounded-2xl text-gray-400 font-bold text-xs uppercase tracking-widest hover:border-indigo-200 hover:text-indigo-400 transition-all flex items-center justify-center space-x-2"
            >
              <FileText className="w-4 h-4" />
              <span>Add Notes & Photo</span>
            </button>
          ) : (
            <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-50 space-y-4 animate-in fade-in zoom-in-95 duration-200">
              <div className="flex items-center justify-between text-gray-400">
                <div className="flex items-center space-x-3">
                  <FileText className="w-5 h-5" />
                  <span className="text-xs font-bold uppercase tracking-widest">Notes & Attachments</span>
                </div>
                <button 
                  type="button" 
                  onClick={() => setShowNotes(false)}
                  className="text-[10px] font-bold text-rose-500 uppercase tracking-widest"
                >
                  Hide
                </button>
              </div>
              
              <textarea 
                placeholder="Add more details..."
                value={note}
                onChange={e => setNote(e.target.value)}
                className="w-full text-sm font-medium focus:outline-none min-h-[80px] bg-gray-50/50 rounded-2xl p-4"
              />

              <div className="flex items-center space-x-3">
                 {attachment ? (
                   <div className="flex items-center space-x-3 w-full">
                     <div className="relative w-16 h-16 rounded-2xl overflow-hidden shadow-sm ring-2 ring-indigo-100 bg-gray-50 flex items-center justify-center">
                        {attachmentUri && (attachmentUri.startsWith('data:image') || attachment?.match(/\.(jpg|jpeg|png|gif|webp)$/i)) ? (
                          <img src={attachmentUri} className="w-full h-full object-cover" alt="attachment" />
                        ) : (
                          <Camera className="w-8 h-8 text-indigo-400" />
                        )}
                        <button 
                          type="button" 
                          onClick={() => {
                            setAttachment(undefined);
                            setAttachmentUri(undefined);
                            setAttachmentFile(null);
                          }}
                          className="absolute top-1 right-1 p-0.5 bg-red-500 text-white rounded-full shadow-lg"
                        >
                          <X className="w-3 h-3" />
                        </button>
                     </div>
                     <div className="flex-1 min-w-0">
                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-tight truncate">{attachment}</p>
                        <button 
                          type="button"
                          onClick={handleViewFile}
                          className="mt-1 flex items-center space-x-1 px-2 py-1 bg-indigo-50 text-indigo-600 rounded-lg text-[9px] font-bold uppercase tracking-wider active:scale-95 transition-transform"
                        >
                          <Eye className="w-3 h-3" />
                          <span>View File</span>
                        </button>
                     </div>
                   </div>
                 ) : (
                   <button 
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="w-16 h-16 rounded-2xl bg-gray-50 border-2 border-dashed border-gray-200 flex flex-col items-center justify-center text-gray-400 hover:bg-gray-100 hover:border-indigo-200 transition-colors"
                   >
                     <Camera className="w-5 h-5 mb-1" />
                     <span className="text-[8px] font-bold uppercase tracking-tighter">Add File</span>
                   </button>
                 )}
                 <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  className="hidden" 
                  accept="image/*"
                 />
                 {!attachment && (
                   <div className="flex-1 flex flex-col justify-center">
                      <p className="text-[10px] font-bold text-gray-400 uppercase tracking-tight">Attachment</p>
                      <p className="text-[10px] text-gray-300 font-medium leading-tight">Attach receipt photo.</p>
                   </div>
                 )}
              </div>
            </div>
          )}
        </div>

        <div className="pt-2">
          <button 
            type="submit"
            className="w-full bg-indigo-600 text-white py-3.5 rounded-2xl font-bold shadow-xl shadow-indigo-100 active:scale-[0.98] transition-transform flex items-center justify-center space-x-2"
          >
            <Check className="w-5 h-5" />
            <span>Save Transaction</span>
          </button>
        </div>
      </form>

      {/* Image Preview Modal */}
      {showPreview && (
        <div className="fixed inset-0 z-[100] bg-black flex flex-col pt-safe animate-in fade-in duration-200">
          <div className="flex items-center justify-between p-4 text-white">
            <button onClick={() => setShowPreview(false)} className="p-2 -ml-2 rounded-full bg-white/10 active:bg-white/20 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <span className="text-sm font-bold uppercase tracking-widest">{attachment}</span>
            <button 
              onClick={async () => {
                if (Capacitor.isNativePlatform() && attachment && !attachment.startsWith('data:')) {
                  const rawUri = await getRawFileUri(attachment);
                  await Share.share({ title: attachment, files: [rawUri] });
                } else if (attachmentUri) {
                  window.open(attachmentUri, '_blank');
                }
              }}
              className="p-2 rounded-full bg-white/10 active:bg-white/20 transition-colors"
            >
              {Capacitor.isNativePlatform() ? <Check className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
            </button>
          </div>
          <div className="flex-1 flex items-center justify-center p-4">
            <img 
              src={attachmentUri} 
              className="max-w-full max-h-full object-contain rounded-lg shadow-2xl" 
              alt="Preview" 
            />
          </div>
          <div className="p-6 text-center text-white/40 text-[10px] font-medium uppercase tracking-widest">
            Tap the top right icon to share or save
          </div>
        </div>
      )}
    </div>
  );
}

